### ISSUE TITLE
Help me fill out the docs

### ISSUE THREAD

**Issue by mholt** [simia-tech/caddy-locale#1]
I've got the docs for this add-on started but need help filling out exactly what it does and being more specific about what is required, what's not, what default values are (if any), and what locale names are acceptable. Also looking for an example (preferably just of the `locale` directive, not whole Caddyfile, if possible).

Can you help?

Here's what I've got so far.

``` markdown

locale detects the client's locale. It sets a header field named Detected-Locale with the value. It also creates a new [replacable value](/docs/placeholders) `{locale}` with the detected locale.

### Syntax

<code class="block"><span class="hl-directive">locale</span> <span class="hl-arg">[<i>locale\_list...</i>]</span> {
    <span class="hl-subdirective">detect</span>    <i>methods...</i>
    <span class="hl-subdirective">cookie</span>    <i>name</i>
    <span class="hl-subdirective">available</span> <i>locale\_list...</i>
    <span class="hl-subdirective">path</span>      <i>base\_path</i>
}</code>

- **locale\_list...** is the list of available locales. The first one will be used as default.
- **methods...** is the list of ways to detect the locale. Allowed values are `cookie` (which reads the locale from a cookie) and `header` (which reads the Accept-Language header).
- **name** is the name of the cookie from which to read the locale.
- **base\_path** is the base path prefix to match, if you want locale detection to be scoped to certain paths only.


### Examples

TODO: Description of what this does

<code class="block"><span class="hl-directive">locale </span> <span class="hl-arg">en de</span> {
    <span class="hl-subdirective">detect</span> cookie header
}</code>
```

Also, what happened to the `{locale}` placeholder? Does this package still create it? (I haven't found it in search results.)

**Comment by phifty** [comment]
Could you give me a hint how to add the placeholder again? In the core-version, I've just extended `middleware/replacer.go`, but I don't know how to add a placeholder from a add-on correctly.

The example would work like this already. You could add the `cookie` directive.

```
<code class="block"><span class="hl-directive">locale </span> <span class="hl-arg">en de</span> {
    <span class="hl-subdirective">detect</span> cookie header
    <span class="hl-subdirective">cookie</span> locale
}</code>
```

In this example, the possible locales are `en` and `de`. The detection first tries the read the locale from a cookie named `locale`. If this doesn't result in a valid locale, the `Accept-Language` header is evaluated. The containing locales are checked in order until the first valid is found. If both detection methods don't find any result, the default locale `en` (first of the available locales) is chosen.

It might make sense to add a minimal example too.

```
locale en de
```

will detect the locale `en` or `de` by `header` and might cover already the major use case.

Last, I would add a section about the `Vary` response header since some users might don't know about it.

```
header / Vary "Accept-Language, Cookie"
```

It's not really part of the locale detection, but it helps to avoid caching problems with the browser. `Vary: Accept-Language` should always be added, if detect method `header` is selected. It covers a rare edge case (when the user changes the browser's language settings), but works pretty precise.
The `Vary: Cookie` is tricky. If the `cookie` detection is used, it needs to be set. Otherwise, the browser wouldn't request new content if the cookie changes. But the browser doesn't differentiate which cookie has changed. That means, if there is a session cookie, the browser cache would turn invalid when it's content change. This could be a problem in some setups.

**Comment by phifty** [comment]
Locale can have the form `en` or `en-US` (separated with a dash).

**Comment by mholt** [comment]
>  Could you give me a hint how to add the placeholder again? In the core-version, I've just extended middleware/replacer.go, but I don't know how to add a placeholder from a add-on correctly.

Here's [an example](https://github.com/mholt/caddy/blob/389a6eb344648a99454f1d18bd8e005969687ca1/middleware/proxy/proxy.go#L98-L100) - this sets a response placeholder, and works only if the ResponseWriter is also a ResponseRecorder.

You don't need a placeholder for a request header since users can just do `{>Header-Name}` to fill in a request header value.

Thanks for the clarification of the docs! So the end result is basically that it sets the Detected-Locale header in the request?

**Comment by phifty** [comment]
Exactly, that is the only modification the add-on does.

I've also added the placeholder again. Is there more to do on my side? I'm gonna be on vacation the next two weeks and don't know how much internet access I'll have.

**Comment by mholt** [comment]
The placeholder looks good, although I'm still not convinced it is necessary, since `{>Detected-Locale}` does the same thing (I think).

Not a showstopper. :smile: Just something to consider to make things simpler in the long run.

Thanks for the details! I'll get them up when I'm back from my trip.

**Comment by mholt** [comment]
Got this committed, thanks!
